/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PostOfferRouteImport } from './routes/post-offer'
import { Route as PostListingRouteImport } from './routes/post-listing'
import { Route as OrderBookRouteImport } from './routes/order-book'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as EscrowRouteImport } from './routes/escrow'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfferIdRouteImport } from './routes/offer.$id'
import { Route as EscrowNewRouteImport } from './routes/escrow.new'
import { Route as EscrowIdRouteImport } from './routes/escrow.$id'
import { Route as EscrowTradeIdRouteImport } from './routes/escrow.trade.$id'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramSetupRouteImport } from './routes/api/public/telegram/setup'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PostOfferRoute = PostOfferRouteImport.update({
  id: '/post-offer',
  path: '/post-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const PostListingRoute = PostListingRouteImport.update({
  id: '/post-listing',
  path: '/post-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderBookRoute = OrderBookRouteImport.update({
  id: '/order-book',
  path: '/order-book',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowRoute = EscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferIdRoute = OfferIdRouteImport.update({
  id: '/offer/$id',
  path: '/offer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowNewRoute = EscrowNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EscrowRoute,
} as any)
const EscrowIdRoute = EscrowIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EscrowRoute,
} as any)
const EscrowTradeIdRoute = EscrowTradeIdRouteImport.update({
  id: '/trade/$id',
  path: '/trade/$id',
  getParentRoute: () => EscrowRoute,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramSetupRoute = ApiPublicTelegramSetupRouteImport.update({
  id: '/api/public/telegram/setup',
  path: '/api/public/telegram/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/escrow': typeof EscrowRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/order-book': typeof OrderBookRoute
  '/post-listing': typeof PostListingRoute
  '/post-offer': typeof PostOfferRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/wallet': typeof WalletRoute
  '/escrow/$id': typeof EscrowIdRoute
  '/escrow/new': typeof EscrowNewRoute
  '/offer/$id': typeof OfferIdRoute
  '/escrow/trade/$id': typeof EscrowTradeIdRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/escrow': typeof EscrowRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/order-book': typeof OrderBookRoute
  '/post-listing': typeof PostListingRoute
  '/post-offer': typeof PostOfferRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/wallet': typeof WalletRoute
  '/escrow/$id': typeof EscrowIdRoute
  '/escrow/new': typeof EscrowNewRoute
  '/offer/$id': typeof OfferIdRoute
  '/escrow/trade/$id': typeof EscrowTradeIdRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/escrow': typeof EscrowRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/order-book': typeof OrderBookRoute
  '/post-listing': typeof PostListingRoute
  '/post-offer': typeof PostOfferRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/wallet': typeof WalletRoute
  '/escrow/$id': typeof EscrowIdRoute
  '/escrow/new': typeof EscrowNewRoute
  '/offer/$id': typeof OfferIdRoute
  '/escrow/trade/$id': typeof EscrowTradeIdRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/escrow'
    | '/marketplace'
    | '/order-book'
    | '/post-listing'
    | '/post-offer'
    | '/settings'
    | '/shop'
    | '/wallet'
    | '/escrow/$id'
    | '/escrow/new'
    | '/offer/$id'
    | '/escrow/trade/$id'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/escrow'
    | '/marketplace'
    | '/order-book'
    | '/post-listing'
    | '/post-offer'
    | '/settings'
    | '/shop'
    | '/wallet'
    | '/escrow/$id'
    | '/escrow/new'
    | '/offer/$id'
    | '/escrow/trade/$id'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/escrow'
    | '/marketplace'
    | '/order-book'
    | '/post-listing'
    | '/post-offer'
    | '/settings'
    | '/shop'
    | '/wallet'
    | '/escrow/$id'
    | '/escrow/new'
    | '/offer/$id'
    | '/escrow/trade/$id'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  EscrowRoute: typeof EscrowRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRoute
  OrderBookRoute: typeof OrderBookRoute
  PostListingRoute: typeof PostListingRoute
  PostOfferRoute: typeof PostOfferRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  WalletRoute: typeof WalletRoute
  OfferIdRoute: typeof OfferIdRoute
  ApiPublicTelegramSetupRoute: typeof ApiPublicTelegramSetupRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-offer': {
      id: '/post-offer'
      path: '/post-offer'
      fullPath: '/post-offer'
      preLoaderRoute: typeof PostOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-listing': {
      id: '/post-listing'
      path: '/post-listing'
      fullPath: '/post-listing'
      preLoaderRoute: typeof PostListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-book': {
      id: '/order-book'
      path: '/order-book'
      fullPath: '/order-book'
      preLoaderRoute: typeof OrderBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrow': {
      id: '/escrow'
      path: '/escrow'
      fullPath: '/escrow'
      preLoaderRoute: typeof EscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/$id': {
      id: '/offer/$id'
      path: '/offer/$id'
      fullPath: '/offer/$id'
      preLoaderRoute: typeof OfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrow/new': {
      id: '/escrow/new'
      path: '/new'
      fullPath: '/escrow/new'
      preLoaderRoute: typeof EscrowNewRouteImport
      parentRoute: typeof EscrowRoute
    }
    '/escrow/$id': {
      id: '/escrow/$id'
      path: '/$id'
      fullPath: '/escrow/$id'
      preLoaderRoute: typeof EscrowIdRouteImport
      parentRoute: typeof EscrowRoute
    }
    '/escrow/trade/$id': {
      id: '/escrow/trade/$id'
      path: '/trade/$id'
      fullPath: '/escrow/trade/$id'
      preLoaderRoute: typeof EscrowTradeIdRouteImport
      parentRoute: typeof EscrowRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/setup': {
      id: '/api/public/telegram/setup'
      path: '/api/public/telegram/setup'
      fullPath: '/api/public/telegram/setup'
      preLoaderRoute: typeof ApiPublicTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EscrowRouteChildren {
  EscrowIdRoute: typeof EscrowIdRoute
  EscrowNewRoute: typeof EscrowNewRoute
  EscrowTradeIdRoute: typeof EscrowTradeIdRoute
}

const EscrowRouteChildren: EscrowRouteChildren = {
  EscrowIdRoute: EscrowIdRoute,
  EscrowNewRoute: EscrowNewRoute,
  EscrowTradeIdRoute: EscrowTradeIdRoute,
}

const EscrowRouteWithChildren =
  EscrowRoute._addFileChildren(EscrowRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  EscrowRoute: EscrowRouteWithChildren,
  MarketplaceRoute: MarketplaceRoute,
  OrderBookRoute: OrderBookRoute,
  PostListingRoute: PostListingRoute,
  PostOfferRoute: PostOfferRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  WalletRoute: WalletRoute,
  OfferIdRoute: OfferIdRoute,
  ApiPublicTelegramSetupRoute: ApiPublicTelegramSetupRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
