/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppTradesRouteImport } from './routes/_app/trades'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPostOfferRouteImport } from './routes/_app/post-offer'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppTradeIdRouteImport } from './routes/_app/trade.$id'
import { Route as AppOfferIdRouteImport } from './routes/_app/offer.$id'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramSetupRouteImport } from './routes/api/public/telegram/setup'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTradesRoute = AppTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPostOfferRoute = AppPostOfferRouteImport.update({
  id: '/post-offer',
  path: '/post-offer',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppTradeIdRoute = AppTradeIdRouteImport.update({
  id: '/trade/$id',
  path: '/trade/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOfferIdRoute = AppOfferIdRouteImport.update({
  id: '/offer/$id',
  path: '/offer/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramSetupRoute = ApiPublicTelegramSetupRouteImport.update({
  id: '/api/public/telegram/setup',
  path: '/api/public/telegram/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/post-offer': typeof AppPostOfferRoute
  '/settings': typeof AppSettingsRoute
  '/trades': typeof AppTradesRoute
  '/wallet': typeof AppWalletRoute
  '/offer/$id': typeof AppOfferIdRoute
  '/trade/$id': typeof AppTradeIdRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/post-offer': typeof AppPostOfferRoute
  '/settings': typeof AppSettingsRoute
  '/trades': typeof AppTradesRoute
  '/wallet': typeof AppWalletRoute
  '/offer/$id': typeof AppOfferIdRoute
  '/trade/$id': typeof AppTradeIdRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/post-offer': typeof AppPostOfferRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/trades': typeof AppTradesRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/offer/$id': typeof AppOfferIdRoute
  '/_app/trade/$id': typeof AppTradeIdRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/post-offer'
    | '/settings'
    | '/trades'
    | '/wallet'
    | '/offer/$id'
    | '/trade/$id'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/post-offer'
    | '/settings'
    | '/trades'
    | '/wallet'
    | '/offer/$id'
    | '/trade/$id'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/post-offer'
    | '/_app/settings'
    | '/_app/trades'
    | '/_app/wallet'
    | '/_app/offer/$id'
    | '/_app/trade/$id'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicTelegramSetupRoute: typeof ApiPublicTelegramSetupRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trades': {
      id: '/_app/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AppTradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/post-offer': {
      id: '/_app/post-offer'
      path: '/post-offer'
      fullPath: '/post-offer'
      preLoaderRoute: typeof AppPostOfferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trade/$id': {
      id: '/_app/trade/$id'
      path: '/trade/$id'
      fullPath: '/trade/$id'
      preLoaderRoute: typeof AppTradeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offer/$id': {
      id: '/_app/offer/$id'
      path: '/offer/$id'
      fullPath: '/offer/$id'
      preLoaderRoute: typeof AppOfferIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/setup': {
      id: '/api/public/telegram/setup'
      path: '/api/public/telegram/setup'
      fullPath: '/api/public/telegram/setup'
      preLoaderRoute: typeof ApiPublicTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppPostOfferRoute: typeof AppPostOfferRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTradesRoute: typeof AppTradesRoute
  AppWalletRoute: typeof AppWalletRoute
  AppOfferIdRoute: typeof AppOfferIdRoute
  AppTradeIdRoute: typeof AppTradeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppPostOfferRoute: AppPostOfferRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTradesRoute: AppTradesRoute,
  AppWalletRoute: AppWalletRoute,
  AppOfferIdRoute: AppOfferIdRoute,
  AppTradeIdRoute: AppTradeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicTelegramSetupRoute: ApiPublicTelegramSetupRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
